# Generated by Django 5.0 on 2026-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_description_payment_membership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Credit/Debit Card')], default='CASH', max_length=20),
        ),
    ]
