# Generated by Django 5.0 on 2026-01-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerprofile',
            name='gym',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialties',
            field=models.TextField(blank=True, help_text='E.g., Yoga, Aerobics, Weight Training, Traditional Dance'),
        ),
    ]
