# Generated by Django 5.0 on 2026-01-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymclass',
            options={'ordering': ['start_time'], 'verbose_name_plural': 'Gym Classes'},
        ),
        migrations.AddField(
            model_name='gymclass',
            name='class_type',
            field=models.CharField(choices=[('YOGA', 'Yoga'), ('AEROBICS', 'Aerobics'), ('WEIGHT_TRAINING', 'Weight Training'), ('TRADITIONAL_DANCE', 'Traditional Dance'), ('SPINNING', 'Spinning'), ('ZUMBA', 'Zumba'), ('PILATES', 'Pilates'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=20)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.gymclass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('gym_class', 'member')},
            },
        ),
        migrations.CreateModel(
            name='ClassWaitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='classes.gymclass')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlisted_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('gym_class', 'member')},
            },
        ),
    ]
