# Generated by Django 5.0 on 2026-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_gymclass_options_gymclass_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbooking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='CONFIRMED', max_length=20),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='class_type',
            field=models.CharField(choices=[('YOGA', 'Yoga'), ('AEROBICS', 'Aerobics'), ('WEIGHT_TRAINING', 'Weight Training'), ('CARDIO', 'Cardio'), ('DANCE', 'Dance'), ('MARTIAL_ARTS', 'Martial Arts'), ('SWIMMING', 'Swimming'), ('CROSSFIT', 'CrossFit')], default='YOGA', max_length=30),
        ),
    ]
