# Generated by Django 5.0 on 2026-01-03 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_date_of_birth_and_more'),
        ('gyms', '0004_gymstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin or gym owner who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admin/Owner approval status'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_gym',
            field=models.ForeignKey(blank=True, help_text='Gym where staff/trainer is requesting access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_staff', to='gyms.gym'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_document',
            field=models.FileField(blank=True, help_text='Document proving gym ownership (for gym owners only)', null=True, upload_to='registration_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
    ]
