# Generated by Django 6.0 on 2025-12-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gym_images/'),
        ),
    ]
