# Generated by Django 5.0 on 2026-01-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_gym_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='corporate_price',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('MAINTENANCE', 'Under Maintenance'), ('BROKEN', 'Broken')], default='WORKING', max_length=20)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='gyms.gym')),
            ],
        ),
        migrations.CreateModel(
            name='GymFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('CARDIO', 'Cardio Equipment'), ('WEIGHTS', 'Weight Training'), ('POOL', 'Swimming Pool'), ('SAUNA', 'Sauna'), ('LOCKER', 'Locker Rooms'), ('SHOWER', 'Showers'), ('PARKING', 'Parking'), ('CAFE', 'Cafe'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='gyms.gym')),
            ],
            options={
                'verbose_name_plural': 'Gym Facilities',
            },
        ),
    ]
