# Generated by Django 5.0 on 2026-01-03 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gym_basic_price_gym_closing_time_gym_corporate_price_and_more'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_family_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='primary_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='members.membership'),
        ),
        migrations.AddField(
            model_name='membership',
            name='qr_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user', 'gym')},
        ),
    ]
