# Generated by Django 5.0 on 2026-01-03 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_gymstaff'),
        ('members', '0002_membership_expires_at_membership_is_family_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='tier',
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Basic Monthly', 'Premium Annual'", max_length=100)),
                ('tier', models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('CORPORATE', 'Corporate'), ('VIP', 'VIP'), ('STUDENT', 'Student'), ('FAMILY', 'Family')], default='BASIC', max_length=20)),
                ('duration', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', '3 Months'), ('SEMI_ANNUAL', '6 Months'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in RWF', max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Number of days this membership lasts')),
                ('description', models.TextField(blank=True, help_text='Benefits and features included')),
                ('is_active', models.BooleanField(default=True, help_text='Is this plan available for purchase?')),
                ('max_family_members', models.IntegerField(default=1, help_text='For family plans, how many members allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='gyms.gym')),
            ],
            options={
                'ordering': ['gym', 'price'],
                'unique_together': {('gym', 'name')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='members.membershipplan'),
        ),
    ]
