# Generated by Django 5.0 on 2026-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_membership_tier_membershipplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipplan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('CORPORATE', 'Corporate')], default='BASIC', max_length=20),
        ),
    ]
